Initial Fix
OnFreund/esphome-fingerprint pull request #1
Opened 2020-10-15 07:43 UTC by loongyh

Haven't initialized the adafruit FP lib yet.

2020-10-15 08:36 UTC, OnFreund reviewed
Looks good.
As for using my changed library in PlatformIO, I know that it's doable (`OnFreund/Adafruit-Fingerprint-Sensor-Library` in the YAML works), but not sure how it's done from a custom component.

2020-10-15 08:36 UTC, OnFreund commented on rxxx.cpp
> +  int finger_id = -1;
Maybe we can initialize to zero to make this unsigned? AFAIK zero is not a valid finger id so it should be ok.

2020-10-15 08:36 UTC, OnFreund commented on rxxx.cpp
> +  if (result == FINGERPRINT_OK) {
Might be better to put `waitingRemoval = true;` before this line. That way if there's some exception afterwards, we're not stuck in an error loop as long as the finger is on the reader.

2020-10-15 08:42 UTC, loongyh commented
> `OnFreund/Adafruit-Fingerprint-Sensor-Library` in the YAML works

I believe it's best if we can import the lib directly in the codegen so that's one less extra step and yaml line for the user.

Have you seen [my reply](https://github.com/loongyh/esphome-fingerprint/issues/7#issuecomment-708965358) regarding submitting a PR to adafruit?

2020-10-15 08:44 UTC, loongyh commented on rxxx.cpp
> +  int finger_id = -1;
Yep my thoughts exactly :) will do

2020-10-15 09:07 UTC, OnFreund commented
> I believe it's best if we can import the lib directly in the codegen

I agree, but I'm assuming the same syntax should work there too.

> Have you seen my reply regarding submitting a PR to adafruit?

Created the PR here: https://github.com/adafruit/Adafruit-Fingerprint-Sensor-Library/pull/89

2020-10-15 23:19 UTC, loongyh commented
Adafruit just merged your stream support, till they release a new version we'd have to use the git url for now. Have updated the PR to initialize the lib.
```
# rxxx.yaml

uart:
  tx_pin: 17
  rx_pin: 16
  baud_rate: 57600

rxxx:
  sensing_pin: 4

binary_sensor:
  - platform: rxxx
    enrolling:
      name: "Enrolling"

sensor:
  - platform: rxxx
    fingerprint_count:
      name: "Fingerprint Count"
    status:
      name: "Status"
    capacity:
      name: "Capacity"
    security_level:
      name: "Security Level"
    last_finger_id:
      name: "Last Finger ID"
    last_confidence:
      name: "Last Confidence"
```

![1](https://user-images.githubusercontent.com/20846761/96195663-e7411f00-0f7f-11eb-8097-8a6a76c5c840.PNG)
![2](https://user-images.githubusercontent.com/20846761/96195668-e8724c00-0f7f-11eb-9d72-147ef8491c5d.PNG)

2020-10-16 05:59 UTC, OnFreund commented
Cool!

How is Last Finger ID zero, though? It's supposed to be set to a positive number of matching a finger.
After we fix this, maybe we can open a PR against ESPHome, and continue there?

2020-10-16 16:09 UTC, loongyh commented
I used the [SFGDemo](http://www.adafruit.com/datasheets/SFGDemoV2.0.rar) program to enrol and it seems they start from 0, whereas the adafruit lib starts from 1. Will investigate further.

2020-10-17 05:44 UTC, OnFreund commented
The adadfuit lib doesn't really "start" from anywhere, they just pass the slot on to the reader without modification. If slot 0 can be used, we might need to initialize `finger_id` to something else in `scan_and_match()`.

2020-10-21 13:08 UTC, OnFreund commented
Don't know if you saw this, but AdaFruit released version 2.0.4 with the stream constructor.

2020-10-21 18:32 UTC, loongyh commented
> The adadfuit lib doesn't really "start" from anywhere, they just pass the slot on to the reader without modification.

Ah yes, I meant in the example enroll.ino in which for some reason `ID #0 not allowed`.

> AdaFruit released version 2.0.4

Nice! Will update the codegen to use it.

2020-10-21 18:39 UTC, OnFreund commented
If 0 is an allowed slot, let's switch to a signed int16 so we can use -1 for an invalid print. It'll still have over 32k positive indexes. Even if you find a reader that supports so many, and enroll a print in just 10 seconds, it will take almost 4 straight days with no breaks just to enroll that many :)

2020-10-21 18:49 UTC, loongyh commented
Hmm I kinda think there's a legit reason the example excluded slot #0.

2020-10-22 05:46 UTC, OnFreund commented
> Hmm I kinda think there's a legit reason the example excluded slot #0.

True, but then again you've showed that you can successfully use index 0...

2020-10-25 14:11 UTC, OnFreund requested changes

2020-10-25 14:11 UTC, OnFreund commented on rxxx.cpp
>    }
Maybe use `&&` instead of nested `if`s?

2020-10-25 14:11 UTC, OnFreund commented on rxxx.cpp
> +    ESP_LOGV(TAG, "Scan and match");
When sensing pin is available, this happens infrequently enough to make it `debug` rather than `verbose`

2020-10-25 14:11 UTC, OnFreund commented on rxxx.cpp
> +  ESP_LOGV(TAG, "Getting image %d", buffer);
Sames here

2020-10-25 14:58 UTC, loongyh commented
> True, but then again you've showed that you can successfully use index 0...

Have implemented back slot #0. Just finished up the initial fix, passed linting and tested working with my full config as follows:

```
# rxxx.yaml
api:
  reboot_timeout: 0s

uart:
  tx_pin: 17
  rx_pin: 16
  baud_rate: 57600

rxxx:
  sensing_pin: 4
  on_finger_scanned:
    - lambda: |-
        if (success) {
          id(rxxx_state).publish_state("Authorized finger " + to_string(finger_id));
        } else {
          if (result == FINGERPRINT_NOTFOUND) {
            id(rxxx_state).publish_state("Unauthorized finger");
          } else {
            id(rxxx_state).publish_state("Error: " + to_string(result));
          }
        }   
  on_enrollment_scan:
    - lambda: |-
        id(rxxx_state).publish_state("Scanned " + to_string(scan_number));
  on_enrollment_done:
    - lambda: |-
        if (success) {
          id(rxxx_state).publish_state("Enrolled into slot " + to_string(finger_id));
        } else {
          id(rxxx_state).publish_state("Error: " + to_string(result));
        } 

binary_sensor:
  - platform: rxxx
    id: rxxx_enrolling
    name: "Rxxx Enrolling"

text_sensor:
  - platform: template
    id: rxxx_state
    name: "Rxxx State"

sensor:
  - platform: rxxx
    fingerprint_count:
      name: "Rxxx Fingerprint Count"
    status:
      name: "Rxxx Status"
    capacity:
      name: "Rxxx Capacity"
    security_level:
      name: "Rxxx Security Level"
    last_finger_id:
      name: "Rxxx Last Finger ID"
    last_confidence:
      name: "Rxxx Last Confidence"
  - platform: homeassistant
    id: hass_input_num
    entity_id: input_number.rxxx
    accuracy_decimals: 0

switch:
  - platform: template
    name: "Rxxx Enroll"
    icon: "mdi:account-plus"
    lambda: !lambda "return id(rxxx_enrolling).state;"
    turn_on_action:
      - rxxx.enroll:
          finger_id: !lambda "return id(hass_input_num).state;"
    turn_off_action:
      - rxxx.cancel_enroll:
  - platform: template
    name: "Rxxx Clear DB"
    icon: "mdi:nuke"
    turn_on_action:
      - rxxx.delete_all:

```

```
# HA configuration.yaml
input_number:
  rxxx:
    name: Slot No.
    icon: mdi:content-save
    min: 0
    max: 200
    mode: box
```

```
# HA ui-lovelace.yaml
views:
  - title: test
    icon: mdi:sign-caution
    cards:
      - type: horizontal-stack
        cards:
        - type: entities
          show_header_toggle: false
          entities:
            - switch.rxxx_enroll
            - input_number.rxxx
            - binary_sensor.rxxx_enrolling
            - sensor.rxxx_state
            - sensor.rxxx_last_finger_id
            - sensor.rxxx_last_confidence
            - sensor.rxxx_fingerprint_count
            - sensor.rxxx_capacity
            - switch.rxxx_clear_db
            - sensor.rxxx_status
            - sensor.rxxx_security_level
```

![1](https://user-images.githubusercontent.com/20846761/97110656-5f90a880-1715-11eb-8fef-941be73bb4fe.PNG)


> After we fix this, maybe we can open a PR against ESPHome, and continue there?

Still need to write up the docs first before we can open the PR, also we have to do it not with this current component-only repo but with the full fork, taking note of the icon additions in `const.py`:
```
# const.py
ICON_ACCOUNT = 'mdi:account'
ICON_ACCOUNT_CHECK = 'mdi:account-check'
ICON_DATABASE = 'mdi:database'
ICON_FINGERPRINT = 'mdi:fingerprint'
ICON_KEY_PLUS = 'mdi:key-plus'
ICON_SECURITY = 'mdi:security'
```

2020-10-25 15:01 UTC, loongyh commented on rxxx.cpp
> +    ESP_LOGV(TAG, "Scan and match");
Do you want to include a conditional check to only logd when sensing pin is not available?

2020-10-25 15:01 UTC, loongyh commented on rxxx.cpp
>    }
Okay

2020-10-25 16:21 UTC, loongyh commented on rxxx.cpp
> +    ESP_LOGV(TAG, "Scan and match");
Added the conditional checks

2020-10-27 22:05 UTC, loongyh commented
Have committed the last of my changes, closed all the issues and it's all ready now :) Can you review and proceed to submit the PR to ESPHome? I'll be unable to work on this for the next 2 weeks starting tomorrow.

2020-10-27 22:24 UTC, loongyh commented
Latest configs as follows:

```
# rxxx.yaml
api:
  reboot_timeout: 0s

uart:
  tx_pin: 17
  rx_pin: 16
  baud_rate: 57600

rxxx:
  sensing_pin: 4
  on_finger_scan_matched:
    - rxxx.aura_led_control:
        state: BREATHING
        speed: 200
        color: BLUE
        count: 1
    - text_sensor.template.publish:
        id: rxxx_state
        state: "Authorized finger"
  on_finger_scan_unmatched:
    - rxxx.aura_led_control:
        state: FLASHING
        speed: 25
        color: RED
        count: 2
    - text_sensor.template.publish:
        id: rxxx_state
        state: "Unauthorized finger"
  on_enrollment_scan:
    - rxxx.aura_led_control:
        state: FLASHING
        speed: 25
        color: BLUE
        count: 2
    - rxxx.aura_led_control:
        state: ALWAYS_ON
        speed: 0
        color: PURPLE
        count: 0
  on_enrollment_done:
    - rxxx.aura_led_control:
        state: BREATHING
        speed: 100
        color: BLUE
        count: 2
    - text_sensor.template.publish:
        id: rxxx_state
        state: "Enrolled fingerprint"
  on_enrollment_failed:
    - rxxx.aura_led_control:
        state: FLASHING
        speed: 25
        color: RED
        count: 4
    - text_sensor.template.publish:
        id: rxxx_state
        state: "Failed to enroll fingerprint"

binary_sensor:
  - platform: rxxx
    id: rxxx_enrolling
    name: "Rxxx Enrolling"

text_sensor:
  - platform: template
    id: rxxx_state
    name: "Rxxx State"

sensor:
  - platform: rxxx
    fingerprint_count:
      name: "Rxxx Fingerprint Count"
    last_finger_id:
      name: "Rxxx Last Finger ID"
    last_confidence:
      name: "Rxxx Last Confidence"
  - platform: homeassistant
    id: hass_input_num
    entity_id: input_number.rxxx
    accuracy_decimals: 0

switch:
  - platform: template
    name: "Rxxx Enroll"
    icon: "mdi:account-plus"
    lambda: !lambda "return id(rxxx_enrolling).state;"
    turn_on_action:
      - rxxx.aura_led_control:
          state: ALWAYS_ON
          speed: 0
          color: PURPLE
          count: 0
      - rxxx.enroll: !lambda "return id(hass_input_num).state;"
    turn_off_action:
      - rxxx.cancel_enroll:
  - platform: template
    name: "Rxxx Delete Fingerprint"
    icon: "mdi:account-minus"
    turn_on_action:
      - rxxx.delete: !lambda "return id(hass_input_num).state;"
  - platform: template
    name: "Rxxx Clear DB"
    icon: "mdi:nuke"
    turn_on_action:
      - rxxx.delete_all:
```

```
# HA configuration.yaml
input_number:
  rxxx:
    name: Slot No.
    icon: mdi:content-save
    min: 0
    max: 200
    mode: box
```

```
# HA ui-lovelace.yaml
views:
  - title: test
    icon: mdi:sign-caution
    cards:
      - type: horizontal-stack
        cards:
        - type: entities
          show_header_toggle: false
          entities:
            - switch.rxxx_enroll
            - input_number.rxxx
            - binary_sensor.rxxx_enrolling
            - sensor.rxxx_state
            - sensor.rxxx_last_finger_id
            - sensor.rxxx_last_confidence
            - sensor.rxxx_fingerprint_count
            - switch.rxxx_delete_fingerprint
            - switch.rxxx_clear_db
```

![1](https://user-images.githubusercontent.com/20846761/97368600-41c66d80-18e6-11eb-998a-48bafe421c57.PNG)

2020-10-28 17:46 UTC, zurpia commented
Great, thanks @loongyh and @OnFreund!. First time testing components on ESPHOME. Any advice? I have used it many times but never tested a new component. Hardware is ready.

2020-10-28 18:29 UTC, loongyh commented
1. Follow the [Contributing guide](https://esphome.io/guides/contributing.html#setting-up-development-environment) to set up the esphome dev environment, then simply clone our repo under the esphome/components directory.
If you have an existing version of esphome installed already, then you can use python virtualenv to containerize it:
```
python3 -m venv ~/esphome-dev
source ~/esphome-dev/bin/activate
pip3 install wheel
git clone https://github.com/esphome/esphome.git
~/esphome-dev/esphome/script/setup
cd ~/esphome-dev/esphome/esphome/components
git clone https://github.com/loongyh/esphome-fingerprint.git
```

2. Refer to the conversation in my PR for the icons to add in ~/esphome-dev/esphome/esphome/const.py, as well as my yaml config examples

3. Whenever you want to compile against this dev build, `source ~/esphome-dev/bin/activate` first and verify the virtualenv is active with the (esphome-dev) shell prompt prefix. You can also check with `esphome version` command, it should show dev version.

2020-10-31 21:41 UTC, loongyh commented
@OnFreund @zurpia Written up the [docs](https://github.com/loongyh/esphome-docs/tree/rxxx-docs), please do review!

2020-11-03 13:16 UTC, merged

2020-11-03 13:18 UTC, loongyh commented
@OnFreund I did a few changes during my pr submission to esphome, this is outdated

2020-11-03 13:19 UTC, OnFreund commented
No worries. Hopefully soon the ESPHome repo would be the canonical source for this anyway :)

2020-11-03 13:21 UTC, loongyh commented
Yep, let's continue from there 😁

2020-11-24 17:35 UTC, hungdo0993 commented
Hello guy, i am testing this component, i have 1 question, the connection for the sensing_pin. Is it the wake up signal (blue wire) from the sensor?

2020-11-24 17:38 UTC, OnFreund commented
@hungdo0993 That's correct

2020-11-24 17:39 UTC, hungdo0993 commented
Thank you for quick reply

2020-11-25 17:04 UTC, hungdo0993 commented
Thank for your component, i have tested it already. Everything is working fine.

2021-01-31 16:18 UTC, DirkTas67 commented
Hello,

Where can I find the information about how to connect this to an ESP8266/ESP32.

Regards,

2021-01-31 16:22 UTC, OnFreund commented
That's not part of esphome yet. You can follow the progress here:
https://github.com/esphome/esphome/pull/1356

2021-05-07 00:17 UTC, harveyyoyo commented
So I got this working with the grow fingerprint component. My issue is that it doesnt pick up the fingerprint most of the time. It just keeps saying no finger. It goes through occasionally. With the arduino adafruit it goes all the time. So there must be something causing this issue.

2021-05-07 05:26 UTC, loongyh commented
@harveyyoyo
1. Which model are you using?
2. Are you using the sensing pin?
3. Did the 'no finger' appear once every second, or does it only appear once after you place your finger on the reader?

2021-05-07 14:35 UTC, harveyyoyo commented
Im using the R307 which does not have a sensing pin. im using a nodemcu as well.
The no finger appears multiple times per second.
OK i just realized I had the sensing pin listed and now removed it so it doesnt keep saying no finger
its still not great on picking up my finger. many times i place my finger there it just doesnt register that my finger is there. it seems moody, which could also mean i have a bad sensor. idk. I never used actually used it with the adafruit code i just tested it that way.  If you have any ideas let me know.
I also have a question. last finger id will always have the last finger print listed. how do i create an unlock automation based on last fingerprint.

2021-05-07 15:28 UTC, loongyh commented
> which could also mean i have a bad sensor.

Do you have another reader to try?

> I also have a question. last finger id will always have the last finger print listed. how do i create an unlock automation based on last fingerprint.

There's an example config to unlock on scan written under the documentation [here](https://next.esphome.io/components/fingerprint_grow.html).

2021-05-14 21:20 UTC, harveyyoyo commented
Turned out to be a bad sensor. The bad one was labeled dy50, had only red wires and the light was green. The new one has colored wires and blue light. dont know if it was an incompatible sensor or a faulty one.,